// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwk9dXMOrIkg8q81zA9hZUI6rM_fZOsdw',
    appId: '1:39858232288:web:f905e626c874cf14702985',
    messagingSenderId: '39858232288',
    projectId: 'my-uni-final-project',
    authDomain: 'my-uni-final-project.firebaseapp.com',
    storageBucket: 'my-uni-final-project.firebasestorage.app',
    measurementId: 'G-QE3JR1H27H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2iTKsMJzdoYTo9KGf0LdOnfcK_jZthOw',
    appId: '1:39858232288:android:730f378cb2a2c36c702985',
    messagingSenderId: '39858232288',
    projectId: 'my-uni-final-project',
    storageBucket: 'my-uni-final-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8JkP-VrGwxUkV__pPT0Og3Qcfg7m_22E',
    appId: '1:39858232288:ios:0dbc7d3eddd65026702985',
    messagingSenderId: '39858232288',
    projectId: 'my-uni-final-project',
    storageBucket: 'my-uni-final-project.firebasestorage.app',
    androidClientId: '39858232288-hgmik64gb8f2mgpcnmm9nsqpoptr0th2.apps.googleusercontent.com',
    iosClientId: '39858232288-73anvt3jspu89gmdujqbt0dq8rdp302t.apps.googleusercontent.com',
    iosBundleId: 'com.example.englens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8JkP-VrGwxUkV__pPT0Og3Qcfg7m_22E',
    appId: '1:39858232288:ios:0dbc7d3eddd65026702985',
    messagingSenderId: '39858232288',
    projectId: 'my-uni-final-project',
    storageBucket: 'my-uni-final-project.firebasestorage.app',
    androidClientId: '39858232288-hgmik64gb8f2mgpcnmm9nsqpoptr0th2.apps.googleusercontent.com',
    iosClientId: '39858232288-73anvt3jspu89gmdujqbt0dq8rdp302t.apps.googleusercontent.com',
    iosBundleId: 'com.example.englens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwk9dXMOrIkg8q81zA9hZUI6rM_fZOsdw',
    appId: '1:39858232288:web:c26bee4a2a09f128702985',
    messagingSenderId: '39858232288',
    projectId: 'my-uni-final-project',
    authDomain: 'my-uni-final-project.firebaseapp.com',
    storageBucket: 'my-uni-final-project.firebasestorage.app',
    measurementId: 'G-8GJR7VFTVM',
  );
}
